### ISSUE TITLE
Password Verification and add Password Constraints

### ISSUE THREAD

**Issue by kulkarni-rajas** [lugnitdgp/PlayPal#20]
Currently the user is asked to type the password only once:
Desired:
Add a new field to the sign up form and ask for the password twice for verification

**Comment by murtaza1112** [comment]
i want to contribute to this issue.

**Comment by murtaza1112** [comment]
also what type of constraints do u want on the password?

**Comment by harshith331** [comment]
minimum 8 characters including a special character  .

**Comment by murtaza1112** [comment]
all right

**Comment by harshith331** [comment]
if you have further queries you can mail me or contact directly
