### ISSUE TITLE
Delete songs within a playlist

### ISSUE THREAD

**Issue by kulkarni-rajas** [lugnitdgp/PlayPal#25]
Add the delete button which deletes the song from the current playlist

**Comment by murtaza1112** [comment]
i want to work on this issue,please assign it to me?

**Comment by harshith331** [comment]
you can start working on this issue and mention everything related to what you have done and want to do further the proposal then will be reviewed . we can't assign you any issue before the official announcement of accepted proposals. if you start working on it now itself you have a better chance of getting accepted

**Comment by murtaza1112** [comment]
so for each issue a different pr?

**Comment by harshith331** [comment]
not necessarily .. whats important is that you solve the issue ..anyway it would be better if you had different pr's

**Comment by v-rohan** [comment]
I would like to work on this issue
